import { IdName } from '@/types/id-name.model';
import { OrganizationCategory } from '@/types/organization-category.model';

const idNames: IdName[] = [
  { id: 1, name: 'Behörde' },
  { id: 2, name: 'Stiftung' },
  { id: 3, name: 'Gemeinde/Stadt' },
  { id: 4, name: 'Naturschutzverein' },
  { id: 5, name: 'Jagdverein' },
  { id: 6, name: 'Unterhaltungsverband' },
  { id: 7, name: 'Fischereiverein' },
  { id: 8, name: 'Landwirtschaftsorganisation' },
  { id: 9, name: 'Waldwirtschaftsverband' },
  { id: 10, name: 'Imkerverein' },
  { id: 11, name: 'Tourismusverband' },
  { id: 12, name: 'Universität Osnabrück' },
  { id: 13, name: 'Hochschule Osnabrück' },
  { id: 14, name: 'Unternehmen' },
  { id: 15, name: 'Heimatverein' },
  { id: 16, name: 'Umweltbildungszentrum' },
  { id: 17, name: 'Klimaschutzinitiative' },
  { id: 18, name: 'Wasserverband' },
  { id: 19, name: 'Abfallentsorgungsverband' },
  { id: 20, name: 'Energiegenossenschaft' },
  { id: 21, name: 'Bürgerinitiative' },
  { id: 22, name: 'Sportverein' },
  { id: 23, name: 'Kulturverein' },
  { id: 24, name: 'Jugendorganisation' },
  { id: 25, name: 'Sozialer Dienstleister' },
  { id: 26, name: 'Krankenversicherungsunternehmen' },
  { id: 27, name: 'Arbeitgeberverband' },
  { id: 28, name: 'Gewerkschaft' },
  { id: 29, name: 'Forschungsinstitut' },
  { id: 30, name: 'Technische Hochschule' },
  { id: 31, name: 'Karitative Organisation' },
  { id: 32, name: 'Bildungswerk' },
  { id: 33, name: 'Kulturstiftung' },
  { id: 34, name: 'Krankenhausverband' },
  { id: 35, name: 'Feuerwehrverein' },
  { id: 36, name: 'Katastrophenschutzorganisation' },
  { id: 37, name: 'Genossenschaftsbank' },
  { id: 38, name: 'Handwerkskammer' },
  { id: 39, name: 'Industrie- und Handelskammer' },
  { id: 40, name: 'Handelsverband' },
  { id: 41, name: 'Naturschutzstiftung' },
  { id: 42, name: 'Verkehrsunternehmen' },
  { id: 43, name: 'Sozialverband' },
  { id: 44, name: 'Schützenverein' },
  { id: 45, name: 'Musikverein' },
  { id: 46, name: 'Wissenschaftlicher Beirat' },
  { id: 47, name: 'Tierschutzverein' },
  { id: 48, name: 'Kunstverein' },
  { id: 49, name: 'Wassersportclub' },
  { id: 50, name: 'Seniorenvereinigung' },
];

export const mockOrganizationCategories: OrganizationCategory[] = idNames.map(
  category => ({
    ...category,
    created_at: '',
    updated_at: '',
    description: category.name.includes('e')
      ? `description of category ${category.name}`
      : null,
  })
);
